### ISSUE TITLE
Error when using Docker container

### ISSUE THREAD

**Issue by DynamoGeek** [wbbaddons/Tims-PackageServer#15]
When using the Docker container, I get the below. Am I doing something wrong here, or is the mentioned module out of date and causing the issue all by itself?
```npm info it worked if it ends with ok
npm info using npm@3.10.8
npm info using node@v7.0.0
npm info lifecycle tims-packageserver@2.1.0-beta.1~prestart: tims-packageserver@2.1.0-beta.1
npm info lifecycle tims-packageserver@2.1.0-beta.1~start: tims-packageserver@2.1.0-beta.1

> tims-packageserver@2.1.0-beta.1 start /usr/src/app
> coffee app.coffee

Error: The module '/usr/src/app/node_modules/node-expat/build/Release/node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
  at Object.Module._extensions..node (module.js:600:18)
  at Module.load (/usr/src/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:449:12)
  at Function.Module._load (module.js:441:3)
  at Module.require (module.js:500:17)
  at require (internal/module.js:20:19)
  at bindings (/usr/src/app/node_modules/bindings/bindings.js:76:44)
  at Object.<anonymous> (/usr/src/app/node_modules/node-expat/lib/node-expat.js:4:32)
  at Module._compile (module.js:573:32)
  at Object.Module._extensions..js (module.js:582:10)
  at Module.load (/usr/src/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:449:12)
  at Function.Module._load (module.js:441:3)
  at Module.require (module.js:500:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/usr/src/app/node_modules/xml-stream/lib/xml-stream.js:2:22)
  at Module._compile (module.js:573:32)
  at Object.Module._extensions..js (module.js:582:10)
  at Module.load (/usr/src/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:449:12)
  at Function.Module._load (module.js:441:3)
  at Module.require (module.js:500:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/usr/src/app/node_modules/xml-stream/index.js:1:80)
  at Module._compile (module.js:573:32)
  at Object.Module._extensions..js (module.js:582:10)
  at Module.load (/usr/src/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:449:12)
  at Function.Module._load (module.js:441:3)
  at Module.require (module.js:500:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/usr/src/app/packageListReader.coffee:25:13)
  at Object.<anonymous> (/usr/src/app/packageListReader.coffee:1:1)
  at Module._compile (module.js:573:32)
  at Object.loadFile (/usr/src/app/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/src/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:449:12)
  at Function.Module._load (module.js:441:3)
  at Module.require (module.js:500:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/usr/src/app/app.coffee:26:21)
  at Object.<anonymous> (/usr/src/app/app.coffee:1:1)
  at Module._compile (module.js:573:32)
  at Object.exports.run (/usr/src/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:162:23)
  at compileScript (/usr/src/app/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/usr/src/app/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/usr/src/app/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/src/app/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:573:32)
  at Object.Module._extensions..js (module.js:582:10)
  at Module.load (module.js:490:32)
  at tryModuleLoad (module.js:449:12)
  at Function.Module._load (module.js:441:3)
  at Module.runMain (module.js:607:10)
  at run (bootstrap_node.js:382:7)
  at startup (bootstrap_node.js:137:9)
  at bootstrap_node.js:497:3


npm info lifecycle tims-packageserver@2.1.0-beta.1~start: Failed to exec start script
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! tims-packageserver@2.1.0-beta.1 start: `coffee app.coffee`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tims-packageserver@2.1.0-beta.1 start script 'coffee app.coffee'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tims-packageserver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee app.coffee
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tims-packageserver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tims-packageserver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

**Comment by TimWolla** [comment]
How do you run the container?

**Comment by DynamoGeek** [comment]
I ran:
sudo docker build -t "wcf-package-server:Dockerfile" .

Then:
sudo docker create -it --name wcf-package-server wcf-package-server:Dockerfile

And then attempted to start the container with:
sudo docker run -p 9001:9001 wcf-package-server:Dockerfile

On Oct 31, 2016, at 2:27 PM, Tim Düsterhus <notifications@github.com<mailto:notifications@github.com>> wrote:


How do you run the container?

**Comment by TimWolla** [comment]
Did you perform these steps in a fresh clone? Did you already have the `node:onbuild` image on your computer?

Running a freshly pulled `wbbaddons/tims-packageserver` from Docker hub works fine for me. You might want to try this as well.

**Comment by DynamoGeek** [comment]
I originally downloaded the zip of the repo and used that, and kept the files in a folder named differently from the repo.

After your comment above, I git pulled the latest repo, and also left them in the folder named the same as the repo.

One of the above things took care of the issue. :)

**Comment by TimWolla** [comment]
My suspicion was a erroneous `node_modules` folder, though the `.dockerignore` in the repository should have taken care of that. 

Anyway, glad that it works now.
